version: '3'

services:

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
    volumes:
      - ./mysql:/var/lib/mysql

  facturascripts:
    image: patrickstigler/facturascripts:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - ./facturascripts:/var/www/html